language: node_js
node_js:
  - 16.13.2
os: linux
addons:
  ssh_known_hosts:
    secure: N8oOSXuRA1lGaE2uIlWcso6R4foxATajG4PI+uVg0J5pjw+xFcMo8+FfhD8zrjcfjNRxIvcY/uNgG8sZ7rnYC4PCuRcwR76Uav3NIDGRIqxCRLH7Jy6g2MpzxIgTODzKO7IFvHstR+3LXGJFwlas3po5+uN4JI2TfbS7MtHwPwYHZcf+KtZMbAqsY7YGeoTOjTnLQ1cIEGjB5TDYXp9PpdR+zMp4U4O6+E+7lonpp250oxoiCicrA0R456ZwOIA8A6AOSFhXK9M2n0C0T90Bbsmp+1w2uxxWA5IGC4Y6xaJgkJE8r5H2cM7aelviCjSZXTFVT/0ptDuJZOjVv1fCks02teSb79vGTTzciCBzl+PtPW/srkQAr1W0jJBmYDs1H2uvp4pzSeb/odyYSNi1P6JGjBG6eK7bJ+4oJecNOewVVQ2qQ3338OcQRnhdMW1F1K90Ib/i83UN3ie2WAyjASO0liJenBsgTaVTv7IfI+uqsDeCi+8Slzm/vt5hrZyCxyPVcKngS5yXs+OvMlkmA06/XoORC81xdyYPfnUTdm18kZOCFaYzVBy2ajHQ+0E/2uWBEBa2L1aOhv91UYRixXxQ9X6uUJtTOjB/k+qpmtAZ7geFfLQdXNAgu21PhBLL2cnd+yROmVnqXg7e2npRxjSAIh5wjTRSy1r+KFG2ejg=
cache:
  npm: true
  directories:
    - ~/.cache
env:
  - CYPRESS_KEY=$cypress_key
install:
  - npm ci
  - npm run cy:verify
  - npm run lint
script:
  - npm run build
  - npm run test:ci
  - npm run cy:ci
deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy/deploy.sh
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
before_deploy:
  - openssl aes-256-cbc -K $encrypted_ce6d252d3043_key -iv $encrypted_ce6d252d3043_iv
    -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
